### PR TITLE
Add accordion component

### LINKED ISSUE #29: Add accordion component
The accordion component is currently missing, and is one of the more useful components and having it would be a good thing.

### PR DESCRIPTION
**Pull request by kbrabrand**
Fixes #29.

Changes proposed in this pull request:
 * Add the accordion components with related tests

Note:
I've been debating (with myself) whether or not to include the state logic needed to handle open/closed state for the AccordionItems in an Accordion, and decided on not including it as it would increase complexity as well as probably making handling the state in your own app mor awkward.

### CODE REVIEW

**Comment by crisu83** [comment]
Thanks for this. Sorry for the delay but this and the previous week has been really hectic for us.

**Comment by Jalle19** [comment]
@kbrabrand would be much appreciated if you could take a look at https://github.com/digiaonline/react-foundation-docs/issues/6 and maybe add some documentation for this component?

**Comment by atroppe** [comment]
Hi any update on the docs? Would really like to use this component. Thanks!

**Comment by crisu83** [comment]
@kbrabrand ping

**Comment by kbrabrand** [comment]
Sorry for the delay. Ended up not using the component in the client project after all, and I was caught up in other things... I've started adding [docs](https://github.com/digiaonline/react-foundation-docs/pull/7), but have an issue that needs sorting out before I can proceed. Help appreciated.

**Pull request merged**
